version: "2"

services:
  rabbitmq:
    image: rabbitmq:3.8.16-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  celery-flower:
    image: mher/flower
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq//
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=test:test
    ports:
      - "5555:5555"
volumes:
  rabbitmq_data:
    driver: local
